### ISSUE TITLE
Post time is not updated automatically

### ISSUE THREAD

**Issue by agazso** [agazso/postmodern#131]
In the card header we display the time when the post was posted in a human readable way (e.g. `15 minutes ago`). It was updated every minute automatically, so it always showed you the correct value. This  update functionality stopped working after #99, so this is a regression.

**Comment by agazso** [comment]
We have a `currentTimestamp` in the app state and a `TICK-TIME` action that updates it. It was supposed to be used for this kind of functionality. If we start using it however, it's possible that it will break the refreshing of the `RefreshableFeed`, last time I disabled it because of that. Maybe that's fixed since then, it needs to be checked.

**Comment by vujevits** [comment]
It was not disabled, I just did not realize there was such a side-effect :-)
it was updating a seemingly unused variable, what I missed that it caused a rerender every minute, so everything re-rendered, and the cards called printableElapsedTime with default parameter Date.now()
I assume the solution should be adding to the Card's props the currentTimestamp, so the cards can re-render without side-effects.
