### ISSUE TITLE
Selecting a feed shows the posts in the feed and your posts too

### ISSUE THREAD

**Issue by agazso** [agazso/postmodern#176]
**Describe the bug**
Selecting a feed shows the posts in the feed and your posts too.

**To Reproduce**
1. Go to the home screen
2. Click on the feed selector
3. Select a feed
4. You should see the selected feeds' post as well as your own posts.

**Expected behavior**
Only the selected feeds' posts should be shown, not your own posts.

**Screenshots**
See screenshot
<img width="487" alt="screen shot 2019-02-23 at 18 07 51" src="https://user-images.githubusercontent.com/230163/53286517-0b8e2d80-3796-11e9-8906-87bb63eca0eb.png">

**Comment by agazso** [comment]
It's because this line:

**Comment by vujevits** [comment]
It was supposed to be a workaround, but it turned out to be a fuckup.
Until the author uri/feedUrl issues are resolved, there should be a separate selector for localPosts/rssPosts
