### ISSUE TITLE
Changing your photo doesn't change your photo in older posts

### ISSUE THREAD

**Issue by agazso** [agazso/postmodern#65]

**Comment by vujevits** [comment]
I thought we agreed on it being a feature 😄

**Comment by agazso** [comment]
Maybe, but how it works currently feels very inconsistent (~buggy):
- if you change your profile picture, it seems that nothing happens, because your old posts still has your old profile picture
- when you post a new post, then it will be shown with your new profile picture
- however if you share the new post, all your old posts will be shown with the updated profile picture to your followers, but not to you

**Comment by vujevits** [comment]
So if we want to go forward with posts containing avatars, I think the following should be the solutions for these problems:

1. I think that's fine
2. when posting, we should show your profile picture and author name, it will be necessary anyway when the users will have multiple feeds (with distinct avatars)
3. that sounds like a bug, a post should point to an avatar and it should be used for display everywhere

I know it's different from what people are used to, but
1. It should be obvious for the users that if they upload something, it won't really go away (immutability). 
2. From my experience, people use temporary profile pictures to communicate things, it's like a meta post, also sometimes part of actual posts, and these jokes/references/etc. get out of context when poeple change back their profile picture.
